############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Legame"
url = "legame/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Licenze"
url = "licenze/"
weight = 2
